version: "3.7"
services: 
    api:
        build: .
        ports: 
            - "8080:8080"
        links: 
            - pgdb
        depends_on: 
            - pgdb
    pgdb:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: api
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/pgsql/data
        volumes: 
            - "/var/lib/pgsql/data:/var/lib/pgsql/data"