version: "3.7"
services:
    api:
        build: .
        ports: 
            - "81:81"
        container_name: api
        networks: 
            - app-network
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on: 
            - pgdb
    pgdb:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: api
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/pgsql/data
        container_name: pgdb
        volumes: 
            - "/var/lib/site/data:/var/lib/pgsql/data"
        networks:
            - app-network
volumes:
    certbot-etc:
    certbot-var:
networks:
    app-network:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "app-network"