version: "3.7"
services: 
    api:
        build: .
        ports: 
            - "8080:8080"
        links: 
            - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: apidata
            PGDATA: /var/lib/pgsql/data
        volumes: 
            - "/var/lib/pgsql/data:/var/lib/pgsql/data"